//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_13st.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaTaiKhoan { get; set; }
        public int idChucNang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
